### ISSUE TITLE
Bug pelo whatsweb.

### ISSUE THREAD

**Issue by pitec0** [lichti/whats-spoofing#3]
It's working perfectly, but in one of the attempts to send the spoofing, when accessing via WhatsWEB I noticed that the conversation no longer opens. In the photo, the conversation window was supposed to be open, but it looks like this.
In the attempt I ended up forgetting to enter the MSG ID, then it stayed like this on the web, on the cell phone it is normal, only on the web it is buggy.
To fix it, I just used the same command and added the MSG ID again. and returned.
I'm just posting to let you know if this happens to anyone else.
![Sem título](https://github.com/lichti/whats-spoofing/assets/142224015/980cc329-0bde-4133-afbe-95e4eea97df3)

**Comment by lichti** [comment]
Esse é mais um bug do whatsapp, quando o campo `Participant` recebe um valor invalido (um valor que não seja um ID de um usuário) alguns clients "quebram". O Whatsapp web deixa de carregar aquele chat e os clients windows e mac fecham o client ao tentar abrir esse chat que possui essa mensagem mal formatada.

Pra solucionar acesse esse chat (1:1 ou grupo) via client do celular e apague essa msg, isso irá resolver o problema.

E seguimos em frente, pois o whatsapp não tem falhas... 

Dica, no campo `msgID` coloque ! para o exploit gerar o ID randomico automáticamente.

**Comment by lichti** [comment]
@pitec0 Sorry, now in English

This is another WhatsApp bug. When the `Participant` field receives an invalid value (a value that is not a user ID), some clients 'break.' WhatsApp Web stops loading that chat, and the Windows and Mac clients close when attempting to open this chat with the malformed message.

To solve this, access this chat (1:1 or group) via the mobile client and delete that message. This will resolve the issue.

And we move on, because WhatsApp has no flaws...

Hint: In the `msgID` field, enter `!` for the exploit to generate the random ID automatically.

**Comment by eldarkace** [comment]
Can you kindly provide me a demo reply code with the `msgID `because I don't know how to type the `msgID` proberly
